language: node_js
sudo: false
cache: npm
jobs:
  include:
    - stage: test
      node_js:
        - 12
        - 11
        - 10
        - 9
        - 8
      script:
        - npm run lint
    - stage: deploy
      node_js: 12
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_AUTH_TOKEN
        on:
          tags: true
