language: node_js
sudo: false
node_js:
  - "12"
  - "10"
  - "8"
cache: npm
jobs:
  include:
    - stage: test
      script:
        - npm run lint
    - stage: deploy
      node_js: "12"
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_AUTH_TOKEN
        on:
          tags: true
          all_branches: true
